import time 

def print_intro():
    print(u"                                                                                                      ")
    time.sleep(0.08)
    print(u"\u001b[36m ,---------.    .-''-.  .-------.    ,---.    ,---.    _______      ____      .---.        _______    ")
    time.sleep(0.08)
    print(u"\u001b[36m \\          \\ .'_ _   \\ |  _ _   \\   |    \\  /    |   /   __  \\   .'  __ `.   | ,_|       /   __  \\   ")
    time.sleep(0.08)
    print(u"\u001b[36m  `--.  ,---'/ ( ` )   '| ( ' )  |   |  ,  \\/  ,  |  | ,_/  \\__) /   '  \\  \\,-./  )      | ,_/  \\__)  ")
    time.sleep(0.08)
    print(u"\u001b[36m     |   \\  . (_ o _)  ||(_ o _) /   |  |\\_   /|  |,-./  )       |___|  /  |\\  '_ '`)  ,-./  )        ")
    time.sleep(0.08)
    print(u"\u001b[36m     :_ _:  |  (_,_)___|| (_,_).' __ |  _( )_/ |  |\\  '_ '`)        _.-`   | > (_)  )  \\  '_ '`)      ")
    time.sleep(0.08)
    print(u"\u001b[36m     (_I_)  '  \\   .---.|  |\\ \\  |  || (_ o _) |  | > (_)  )  __ .'   _    |(  .  .-'   > (_)  )  __  ")
    time.sleep(0.08)
    print(u"\u001b[36m    (_(=)_)  \\  `-'    /|  | \\ `'   /|  (_,_)  |  |(  .  .-'_/  )|  _( )_  | `-'`-'|___(  .  .-'_/  ) ")
    time.sleep(0.08)
    print(u"\u001b[36m     (_I_)    \\       / |  |  \\    / |  |      |  | `-'`-'     / \\ (_ o _) /  |        \\`-'`-'     /  ")
    time.sleep(0.08)
    print(u"\u001b[36m     '---'     `'-..-'  ''-'   `'-'  '--'      '--'   `._____.'   '.(_,_).'   `--------`  `._____.'   ")
    time.sleep(0.08)
    print(u"\u001b[36m                                                                                                      ")
    time.sleep(0.08)
    print(u"\u001b[36m======================================================================================================")
    time.sleep(0.08)
    print(u"\u001b[36m                                                                                                      ")
    time.sleep(0.08)
    print(u"\u001b[35;1mTermCalc v1.03 - made by Cetin Cetindag")
    time.sleep(0.1)
    print(u"\u001b[33mGet the repository by visiting github.com/cetincetindag/term-calc")
    print(u"=======================USAGE=AND=COMMANDS=============================================================")
    time.sleep(0.1)
    print(u"- Just type your equation using +, -, / and * without minding operator precedence and spaces.")
    time.sleep(0.1)
    print("======== Example : 25+385-334/349*3495")
    time.sleep(0.1)
    print("- The CLI will automatically give you the result of your input.")
    time.sleep(0.1)
    print("- You can store the result of your last calculation in a variable by typing x,y or z after the prompt.")
    time.sleep(0.1)
    print("- You can then use your new variable in the next equation simply by adding it to your equation.")
    time.sleep(0.1)
    print("======== Example : x*9+12-220")
    time.sleep(0.1)
    print("- Here are the simple commands for basic operations of the calculator:")
    time.sleep(0.1)
    print("- Clear Everyting = c ")
    time.sleep(0.1)
    print("- New Calculation = n (does not clear previously stored variables)")
    time.sleep(0.1)
    print("- Store in a variable = s (You will be prompted to choose a variable after inputting 's') ")
    time.sleep(0.1)
    print("- You can type exit at any moment to quit out of the script!                              ")
    time.sleep(0.1)
    print("------------------------------------------------------------------------------------------------------")
    time.sleep(0.1)
    print("---More advanced functions like logarithms, sqroot and trigonometry are currently under development---")
    time.sleep(0.1)
    print("....Have fun !...")
    time.sleep(0.1)
